name: Build

on:
  push:
    branches:
    - master
    - actions

jobs:
  phpunit:
    name: PHPUnit with Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install backend dependencies
      run: composer install --prefer-dist --no-interaction
    - name: Run PHPUnit
      run: composer coverage
    - name: Upload coverage reports
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash)
