name: CI

on:
  push:
    branches:
    - master
    - actions

jobs:
  phpunit:
    name: PHPUnit with Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Composer
      run: composer install --no-interaction
    - name: PHPUnit
      run: composer coverage
    - name: Codecov
      run: |
        vendor/bin/test-reporter
        bash <(curl -s https://codecov.io/bash)
